# Generated by Django 6.0.7 on 2026-07-26 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Food",
            fields=[
                ("id", models.CharField(primary_key=True, serialize=False)),
                ("food_cd", models.CharField(unique=True)),
                ("group_name_major", models.CharField()),
                ("group_name_minor", models.CharField()),
                ("food_name", models.CharField()),
                ("research_year", models.PositiveIntegerField()),
                ("maker_name", models.CharField()),
                ("ref_name", models.CharField()),
                ("serving_size", models.CharField()),
                ("serving_size_unit", models.CharField()),
                ("calorie", models.DecimalField(decimal_places=2, max_digits=8)),
                ("carbohydrate", models.DecimalField(decimal_places=2, max_digits=8)),
                ("protein", models.DecimalField(decimal_places=2, max_digits=8)),
                ("fat", models.DecimalField(decimal_places=2, max_digits=8)),
                ("sugars", models.DecimalField(decimal_places=2, max_digits=8)),
                ("sodium", models.DecimalField(decimal_places=2, max_digits=8)),
                ("cholesterol", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "saturated_fatty_acids",
                    models.DecimalField(decimal_places=2, max_digits=8),
                ),
                ("trans_fat", models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
    ]
